			HookCapabilityDefinition(
				id: "call_local_llm",
				description: "General purpose LLM invocation.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.call_local_llm",
				requires: "prompt",
				produces: "llm_output",
				cost: "normal",
				safety: "safe",
				whenToUse: "General purpose LLM invocation.",
				whenNotToUse: "When specific heuristic hooks work."
			),
			HookCapabilityDefinition(
				id: "summarize_with_llm",
				description: "LLM-based summarization.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.summarize_with_llm",
				requires: "text",
				produces: "summary",
				cost: "normal",
				safety: "safe",
				whenToUse: "LLM-based summarization.",
				whenNotToUse: "When text is short."
			),
			HookCapabilityDefinition(
				id: "classify_with_llm",
				description: "LLM-based classification.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.classify_with_llm",
				requires: "text",
				produces: "classification",
				cost: "normal",
				safety: "safe",
				whenToUse: "LLM-based classification.",
				whenNotToUse: "When regex works."
			),
			HookCapabilityDefinition(
				id: "extract_structured_json_with_llm",
				description: "Extract JSON via LLM.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "extraction.extract_structured_json_with_llm",
				requires: "text",
				produces: "json",
				cost: "normal",
				safety: "safe",
				whenToUse: "Extract JSON via LLM.",
				whenNotToUse: "When data is simple."
			),
			HookCapabilityDefinition(
				id: "critique_result_with_llm",
				description: "LLM-based critique.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.critique_result_with_llm",
				requires: "text",
				produces: "critique",
				cost: "normal",
				safety: "safe",
				whenToUse: "LLM-based critique.",
				whenNotToUse: "For straightforward results."
			),
			HookCapabilityDefinition(
				id: "verify_output_with_llm",
				description: "Verify output via LLM.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.verify_output_with_llm",
				requires: "text",
				produces: "verification",
				cost: "normal",
				safety: "safe",
				whenToUse: "Verify output via LLM.",
				whenNotToUse: "When deterministic checks exist."
			),
			HookCapabilityDefinition(
				id: "generate_short_response",
				description: "Generate brief text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "transformation.generate_short_response",
				requires: "prompt",
				produces: "short_response",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Generate brief text.",
				whenNotToUse: "When needing long details."
			),
			HookCapabilityDefinition(
				id: "generate_long_response",
				description: "Generate detailed text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "transformation.generate_long_response",
				requires: "prompt",
				produces: "long_response",
				cost: "expensive",
				safety: "safe",
				whenToUse: "Generate detailed text.",
				whenNotToUse: "When brief text suffices."
			),
			HookCapabilityDefinition(
				id: "web_search",
				description: "Perform web search.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "observation.web_search",
				requires: "query",
				produces: "search_results",
				cost: "normal",
				safety: "safe",
				whenToUse: "Perform web search.",
				whenNotToUse: "When local context suffices."
			),
			HookCapabilityDefinition(
				id: "fetch_page_text",
				description: "Fetch text from URL.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "observation.fetch_page_text",
				requires: "url",
				produces: "page_text",
				cost: "normal",
				safety: "safe",
				whenToUse: "Fetch text from URL.",
				whenNotToUse: "When URL is untrusted."
			),
			HookCapabilityDefinition(
				id: "summarize_web_page",
				description: "Summarize web page.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.summarize_web_page",
				requires: "page_text",
				produces: "page_summary",
				cost: "normal",
				safety: "safe",
				whenToUse: "Summarize web page.",
				whenNotToUse: "When full text is needed."
			),
			HookCapabilityDefinition(
				id: "extract_search_results",
				description: "Extract links from search.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "extraction.extract_search_results",
				requires: "search_results",
				produces: "search_links",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Extract links from search.",
				whenNotToUse: "When taking first result directly."
			),
			HookCapabilityDefinition(
				id: "compare_web_sources",
				description: "Compare web pages.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.compare_web_sources",
				requires: "multiple_page_texts",
				produces: "comparison",
				cost: "expensive",
				safety: "safe",
				whenToUse: "Compare web pages.",
				whenNotToUse: "When one source is enough."
			),
			HookCapabilityDefinition(
				id: "extract_article_content",
				description: "Extract article body.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "extraction.extract_article_content",
				requires: "page_text",
				produces: "article_content",
				cost: "normal",
				safety: "safe",
				whenToUse: "Extract article body.",
				whenNotToUse: "When page is not an article."
			),
			HookCapabilityDefinition(
				id: "detect_paywall",
				description: "Check for paywall.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.detect_paywall",
				requires: "page_text",
				produces: "paywall_status",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Check for paywall.",
				whenNotToUse: "When page is known free."
			),
			HookCapabilityDefinition(
				id: "identify_primary_topic",
				description: "Identify main topic.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.identify_primary_topic",
				requires: "page_text",
				produces: "topic",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Identify main topic.",
				whenNotToUse: "When topic is obvious."
			),
			HookCapabilityDefinition(
				id: "get_current_url",
				description: "Get active tab URL.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "observation.get_current_url",
				requires: "none",
				produces: "url",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Get active tab URL.",
				whenNotToUse: "When browser is not active."
			),
			HookCapabilityDefinition(
				id: "open_new_tab",
				description: "Open new browser tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.open_new_tab",
				requires: "url",
				produces: "tab_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Open new browser tab.",
				whenNotToUse: "When avoiding disruptive UI changes."
			),
			HookCapabilityDefinition(
				id: "switch_tab",
				description: "Switch to existing tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.switch_tab",
				requires: "tab_id",
				produces: "tab_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Switch to existing tab.",
				whenNotToUse: "When tab is already active."
			),
			HookCapabilityDefinition(
				id: "close_tab",
				description: "Close active tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.close_tab",
				requires: "tab_id",
				produces: "tab_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Close active tab.",
				whenNotToUse: "When needing tab history."
			),
			HookCapabilityDefinition(
				id: "search_in_current_tab",
				description: "Search in current tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.search_in_current_tab",
				requires: "query",
				produces: "search_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Search in current tab.",
				whenNotToUse: "When search should be in background."
			),
			HookCapabilityDefinition(
				id: "navigate_to_url",
				description: "Navigate active tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.navigate_to_url",
				requires: "url",
				produces: "nav_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Navigate active tab.",
				whenNotToUse: "When page is already loaded."
			),
			HookCapabilityDefinition(
				id: "read_page_title",
				description: "Read browser page title.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "observation.read_page_title",
				requires: "none",
				produces: "title",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Read browser page title.",
				whenNotToUse: "When window title suffices."
			),
			HookCapabilityDefinition(
				id: "read_browser_visible_text",
				description: "Read visible web text.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "observation.read_browser_visible_text",
				requires: "none",
				produces: "text",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Read visible web text.",
				whenNotToUse: "When AX text suffices."
			),
			HookCapabilityDefinition(
				id: "fill_web_field",
				description: "Fill form field.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.fill_web_field",
				requires: "field_data",
				produces: "fill_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Fill form field.",
				whenNotToUse: "When form is sensitive."
			),
			HookCapabilityDefinition(
				id: "submit_form",
				description: "Submit active form.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.submit_form",
				requires: "none",
				produces: "submit_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Submit active form.",
				whenNotToUse: "When submission causes side effects."
			),
			HookCapabilityDefinition(
				id: "draft_email",
				description: "Draft an email.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "transformation.draft_email",
				requires: "notes",
				produces: "email_draft",
				cost: "normal",
				safety: "safe",
				whenToUse: "Draft an email.",
				whenNotToUse: "When short chat message suffices."
			),
			HookCapabilityDefinition(
				id: "summarize_email_thread",
				description: "Summarize email thread.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.summarize_email_thread",
				requires: "email_thread",
				produces: "thread_summary",
				cost: "normal",
				safety: "safe",
				whenToUse: "Summarize email thread.",
				whenNotToUse: "When thread is 1-2 messages."
			),
			HookCapabilityDefinition(
				id: "extract_email_action_items",
				description: "Extract action items.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "extraction.extract_email_action_items",
				requires: "email_text",
				produces: "action_items",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Extract action items.",
				whenNotToUse: "When email has no requests."
			),
			HookCapabilityDefinition(
				id: "prepare_reply",
				description: "Draft an email reply.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "transformation.prepare_reply",
				requires: "email_thread",
				produces: "reply_draft",
				cost: "normal",
				safety: "safe",
				whenToUse: "Draft an email reply.",
				whenNotToUse: "When replying is not needed."
			),
			HookCapabilityDefinition(
				id: "prepare_followup",
				description: "Draft a followup.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "transformation.prepare_followup",
				requires: "email_thread",
				produces: "followup_draft",
				cost: "normal",
				safety: "safe",
				whenToUse: "Draft a followup.",
				whenNotToUse: "When thread is active."
			),
			HookCapabilityDefinition(
				id: "create_message_summary",
				description: "Summarize chat message.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.create_message_summary",
				requires: "message_text",
				produces: "message_summary",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Summarize chat message.",
				whenNotToUse: "When message is short."
			),
			HookCapabilityDefinition(
				id: "open_app",
				description: "Launch an application.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.open_app",
				requires: "app_name",
				produces: "app_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Launch an application.",
				whenNotToUse: "When app is already open."
			),
			HookCapabilityDefinition(
				id: "focus_app",
				description: "Bring app to front.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.focus_app",
				requires: "app_name",
				produces: "app_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Bring app to front.",
				whenNotToUse: "When app is already focused."
			),
			HookCapabilityDefinition(
				id: "quit_app",
				description: "Quit an application.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.quit_app",
				requires: "app_name",
				produces: "app_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Quit an application.",
				whenNotToUse: "When app should remain running."
			),
			HookCapabilityDefinition(
				id: "switch_window",
				description: "Switch app window.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.switch_window",
				requires: "window_id",
				produces: "window_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Switch app window.",
				whenNotToUse: "When single window is active."
			),
			HookCapabilityDefinition(
				id: "press_shortcut",
				description: "Simulate keyboard shortcut.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.press_shortcut",
				requires: "shortcut",
				produces: "shortcut_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Simulate keyboard shortcut.",
				whenNotToUse: "When UI element can be clicked instead."
			),
			HookCapabilityDefinition(
				id: "scroll_view",
				description: "Scroll the active view.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.scroll_view",
				requires: "direction",
				produces: "scroll_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Scroll the active view.",
				whenNotToUse: "When entire content is visible."
			),
			HookCapabilityDefinition(
				id: "click_screen_coordinate",
				description: "Click X/Y coordinate.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.click_screen_coordinate",
				requires: "coordinates",
				produces: "click_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Click X/Y coordinate.",
				whenNotToUse: "When element ID is available."
			),
			HookCapabilityDefinition(
				id: "click_ui_element_by_id",
				description: "Click UI element by ID.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.click_ui_element_by_id",
				requires: "element_id",
				produces: "click_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Click UI element by ID.",
				whenNotToUse: "When no UI map exists."
			),
			HookCapabilityDefinition(
				id: "type_text",
				description: "Simulate keystrokes.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.type_text",
				requires: "text",
				produces: "type_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Simulate keystrokes.",
				whenNotToUse: "When pasting is better."
			),
			HookCapabilityDefinition(
				id: "clear_text_field",
				description: "Clear text field.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "computerControl.clear_text_field",
				requires: "element_id",
				produces: "clear_status",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Clear text field.",
				whenNotToUse: "When field is already empty."
			),
			HookCapabilityDefinition(
				id: "split_goal_into_subtasks",
				description: "Split complex goal.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.split_goal_into_subtasks",
				requires: "goal",
				produces: "subtasks",
				cost: "normal",
				safety: "safe",
				whenToUse: "Split complex goal.",
				whenNotToUse: "When goal is simple."
			),
			HookCapabilityDefinition(
				id: "run_subtasks_parallel",
				description: "Run tasks in parallel.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "dangerous.run_subtasks_parallel",
				requires: "subtasks",
				produces: "results",
				cost: "expensive",
				safety: "requires_confirmation",
				whenToUse: "Run tasks in parallel.",
				whenNotToUse: "When sequential execution is required."
			),
			HookCapabilityDefinition(
				id: "merge_results",
				description: "Merge subtask results.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.merge_results",
				requires: "multiple_results",
				produces: "merged_result",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Merge subtask results.",
				whenNotToUse: "When results are singular."
			),
			HookCapabilityDefinition(
				id: "rank_results",
				description: "Rank multiple items.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.rank_results",
				requires: "results",
				produces: "ranked_results",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Rank multiple items.",
				whenNotToUse: "When items are inherently ordered."
			),
			HookCapabilityDefinition(
				id: "verify_result",
				description: "Verify final result.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "reasoning.verify_result",
				requires: "result",
				produces: "verification_status",
				cost: "cheap",
				safety: "safe",
				whenToUse: "Verify final result.",
				whenNotToUse: "When verification is trivial."
			),
			HookCapabilityDefinition(
				id: "retry_once",
				description: "Retry a failed hook.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "dangerous.retry_once",
				requires: "failed_hook",
				produces: "retry_status",
				cost: "normal",
				safety: "requires_confirmation",
				whenToUse: "Retry a failed hook.",
				whenNotToUse: "When failure is deterministic."
			),
			HookCapabilityDefinition(
				id: "branch_on_result",
				description: "Branch execution path.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				capability: "dangerous.branch_on_result",
				requires: "condition",
				produces: "branch_path",
				cost: "cheap",
				safety: "requires_confirmation",
				whenToUse: "Branch execution path.",
				whenNotToUse: "When execution is linear."
			),