import Foundation

enum ProposalAttemptScope {
	@TaskLocal static var currentId: String?
}

enum TaskInferenceSkipReason: String, Sendable {
	case modelUnavailable = "model_unavailable"
	case timeout
	case lowContext = "low_context"
	case parseFailed = "parse_failed"
}

enum TaskInferenceParseFailure: String, Sendable {
	case parseNoJSONObject = "parse_no_json_object"
	case parseMalformedJSON = "parse_malformed_json"
	case parseMissingRequiredKey = "parse_missing_required_key"
	case parseForbiddenKeys = "parse_forbidden_keys"
}

/// Model-facing task inference for the hot path.
///
/// Hardened contract:
/// - The model outputs ONLY a goal (`g`) plus capability categories (`needCats`).
/// - No hook IDs, no allow-lists, no user-facing question templates.
struct TaskInferenceResult: Sendable, Equatable {
	let shouldChime: Bool
	/// Freeform user goal label generated by the small model (compact key `g`).
	let possibleUserGoal: String
	let confidence: Double
	/// Capability categories requested by the model (compact key `needCats`).
	/// Example: ["context","extract","reason","output"].
	let neededCapabilityCategories: [String]
	/// Optional short explanation for why now / timing.
	let whyNow: String
	/// Optional missing context signal (non-escalation; user-provided context).
	let missingContext: [String]
	let expirySeconds: TimeInterval
	let createdAt: Date

	/// Context types the model explicitly requested (c=0 with need=[...]).
	/// Non-empty signals the engine should gather more context before re-running inference.
	/// Allowed values: "visible_ocr", "ax_window_text", "browser_text", "selected_text", "clipboard_if_relevant"
	let need: [String]
	let needReason: String?
}

// MARK: - Tolerant decode (all optional; resolve to safe defaults)
//
// Supports both verbose keys (full names) and compact single-letter keys:
//   c       → chime/shouldChime
//   g       → goal
//   p       → confidence/probability
//   need    → context escalation request list
//   needCats→ capability categories (no hook IDs)

struct TaskInferenceTolerantOutput: Decodable, Sendable {
	// Chime
	let shouldChime: Bool?
	let shouldChimeIn: Bool?
	let c: Int?

	// Goal
	let possibleUserGoal: String?
	let goal: String?
	let g: String?

	// Confidence
	let confidence: Double?
	let conf: Double?
	let p: Double?

	// Evidence
	let evidenceSummary: String?
	let evidence: String?

	// Capability categories (no hook IDs)
	let neededCapabilityCategories: [String]?
	let needCats: [String]?

	// Why now
	let whyNow: String?
	let why: String?

	// Missing context
	let missingContext: [String]?
	let missing: [String]?

	// Expiry
	let expirySeconds: Double?
	let expiry: Double?

	// Context escalation request (PART A)
	// Model outputs c=0 + need=[...] when context is too weak for confident inference.
	let need: [String]?
	let needReason: String?

	// MARK: - Resolved properties

	var resolvedShouldChime: Bool {
		if let b = shouldChime { return b }
		if let b = shouldChimeIn { return b }
		if let i = c { return i != 0 }
		return false
	}
	var resolvedGoal: String { possibleUserGoal ?? goal ?? g ?? "" }
	var resolvedConfidence: Double { confidence ?? conf ?? p ?? 0 }
	var resolvedWhyNow: String { whyNow ?? why ?? "" }
	var resolvedMissing: [String] { missingContext ?? missing ?? [] }
	var resolvedExpirySeconds: Double { expirySeconds ?? expiry ?? 20 }
	var resolvedNeed: [String] { need ?? [] }
	var resolvedNeedReason: String? { needReason }
	var resolvedNeedCats: [String] { neededCapabilityCategories ?? needCats ?? [] }
}

// MARK: - Semantic validity

/// Coarse quality category assigned AFTER successful JSON parsing.
/// Lets the engine distinguish real intelligence from schema echo.
enum TaskInferenceSemanticValidity: String, Sendable {
	/// Good to use — real values, believable confidence.
	case valid
	/// Model copied placeholder words from the schema (e.g. "goal", "object", "hook_id").
	/// Triggers one retry with a correction prompt.
	case placeholder
	/// Model echoed generic training-data phrases ("Summarize this?", "Compare these?") on a
	/// page where context doesn't support the output. Triggers one retry.
	case exampleLeakage = "example_leakage"
	/// c=1 but q/goal contains no words from the actual title/app/selection.
	/// The model generated something not grounded in the current context. Triggers one retry.
	case ungroundedOutput = "ungrounded_output"
	/// Output used forbidden keys for this contract (e.g. hooks/ids/question fields).
	case forbiddenKeys = "forbidden_keys"
}

/// Stateless validator: examines a parsed `TaskInferenceResult` for placeholder contamination.
enum TaskInferenceSemanticValidator {

	// MARK: - Placeholder word sets

	private static let placeholderGoals: Set<String> = [
		"goal", "user goal", "user's goal", "the goal", "a goal", "help", "task goal",
		"g", "goal here", "specific goal", "fill goal here", "actual goal", "some goal",
		"<goal>", "[goal]", "your goal"
	]
	private static let placeholderVerbs: Set<String> = [
		"verb", "action verb", "suggest help", "action", "suggest", "a verb", "verb here",
		"specific verb", "fill verb", "<verb>", "[verb]", "your verb", "act"
	]

	/// Generic training-data phrases that appear context-free on any page.
	/// These are NOT prompt-specific — they come from the model's training on assistant corpora.
	private static let genericLeakagePhrases: [String] = [
		"summarize this?", "summarize this page?", "summarize this article?",
		"compare these?", "compare these options?", "compare these items?",
		"explain this?", "explain this error?", "explain this code?",
		"want me to summarize?", "want me to compare?", "want me to explain?",
		"shall i summarize?", "shall i compare?", "should i summarize?",
		"help with this?", "help with this page?",
	]

	// MARK: - Validation

	static func validate(
		_ result: TaskInferenceResult,
		windowTitle: String = "",
		appName: String = "",
		selectedText: String? = nil
	) -> TaskInferenceSemanticValidity {
		// c=0 is always valid — intentional silence or a context request.
		guard result.shouldChime else { return .valid }

		// Placeholder detection (c=1 only).
		if isPlaceholderOutput(result) { return .placeholder }

		// Generic training-data leakage: common generic phrases echoed regardless of context.
		if isGenericLeakage(result, windowTitle: windowTitle) { return .exampleLeakage }

		// Grounding check: if c=1, output should mention words from actual context.
		// Only apply when we have enough context to check against.
		let hasRichContext = !windowTitle.isEmpty || selectedText != nil
		if hasRichContext, isUngroundedOutput(result, windowTitle: windowTitle, appName: appName, selectedText: selectedText) {
			return .ungroundedOutput
		}

		return .valid
	}

	// MARK: - Placeholder detection

	static func isPlaceholderOutput(_ r: TaskInferenceResult) -> Bool {
		if placeholderGoals.contains(normalize(r.possibleUserGoal)) { return true }
		if r.confidence == 0.0 { return true }
		// If the model returns only schema-y category words, treat as placeholder.
		let cats = Set(r.neededCapabilityCategories.map { normalize($0) })
		if cats.isEmpty { return true }
		if cats == ["context","extract","reason","output"] { /* ok */ }
		return false
	}

	// MARK: - Generic leakage detection

	/// Detects common training-data phrases that don't reference real page context.
	static func isGenericLeakage(_ r: TaskInferenceResult, windowTitle: String) -> Bool {
		// With the hardened contract there is no `q` field. Use goal text only.
		let g = normalize(r.possibleUserGoal)
		guard !g.isEmpty else { return false }

		// Step 1: Exact matches are always leakage.
		// These are generic, training-data patterns that are not acceptable as user-facing proposals.
		if genericLeakagePhrases.contains(g) {
			return true
		}

		// Step 2: Very short questions (≤ 12 chars) like "Compare?" are almost always context-free.
		guard g.count <= 12 else { return false }

		// Step 3: If the output's substantive words overlap with the title, it's legitimate.
		// This allows short but grounded questions like "Compare?" when the title contains
		// strong overlap words (e.g. "Compare iPhone 16 vs Pixel 10").
		if !windowTitle.isEmpty {
			let contextWords = substantiveWords(from: windowTitle.lowercased())
			if !contextWords.isEmpty {
				let outputWords = substantiveWords(from: r.possibleUserGoal.lowercased())
				if !outputWords.isDisjoint(with: contextWords) {
					return false  // Has overlap → output references real context words
				}
			}
		}

		return true
	}

	// MARK: - Grounding check

	/// Returns true when the model's output (q + goal + object) shares no substantive words
	/// with the actual context (title + app + selection). This indicates the model generated
	/// a response from training patterns rather than actual context.
	///
	/// Only applied when we have enough context to check against (title non-empty).
	static func isUngroundedOutput(
		_ r: TaskInferenceResult,
		windowTitle: String,
		appName: String,
		selectedText: String?
	) -> Bool {
		// Build the context word set from real signals.
		var contextParts = [windowTitle, appName]
		if let sel = selectedText { contextParts.append(sel) }
		let contextWords = substantiveWords(from: contextParts.joined(separator: " "))

		// Must have enough context words to make a meaningful check.
		guard contextWords.count >= 2 else { return false }

		// Build the output word set.
		let outputWords = substantiveWords(from: r.possibleUserGoal.lowercased())

		// If there's ANY overlap → grounded.
		return outputWords.isDisjoint(with: contextWords)
	}

	// MARK: - Helpers

	private static func normalize(_ s: String) -> String {
		s.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
	}

	/// Extracts words ≥ 4 chars that aren't common stopwords. Used for grounding checks.
	static func substantiveWords(from text: String) -> Set<String> {
		let stopwords: Set<String> = [
			"this", "that", "with", "from", "have", "will", "your", "what", "want",
			"page", "here", "help", "more", "like", "just", "them", "they", "when",
			"some", "about", "which", "their", "there", "these", "those", "been",
			"said", "does", "make", "into", "than", "then", "time", "only", "also",
		]
		let words = text.lowercased()
			.components(separatedBy: CharacterSet.alphanumerics.inverted)
			.filter { $0.count >= 4 }
			.filter { !stopwords.contains($0) }
		return Set(words)
	}

	// MARK: - Legacy: example leakage (kept for test backward compat, uses generic check now)

	static func isExampleLeakage(_ r: TaskInferenceResult, windowTitle: String) -> Bool {
		isGenericLeakage(r, windowTitle: windowTitle)
	}
}
