    static func foundationalCatalog() -> [HookCapabilityDefinition] {
        [
			HookCapabilityDefinition(
				id: "observe_current_context",
				description: "Captures a snapshot of the active window/app state.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_window_title",
				description: "Reads the title of the active window.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_selected_text",
				description: "Retrieves any user-selected text.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_clipboard",
				description: "Reads the current contents of the system clipboard.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_ax_text",
				description: "Extracts text directly from the macOS Accessibility API.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "run_ocr_once",
				description: "Captures a screen snapshot and runs Optical Character Recognition.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_current_context",
				description: "Produces a general summary of the immediate context.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_entities",
				description: "Identifies names, places, and organizations.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_product_attributes",
				description: "Extracts specific product details (brands, specs).",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_prices",
				description: "Finds monetary values and pricing structures.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_dates",
				description: "Locates timestamps and calendar dates.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_errors",
				description: "Captures stack traces, crash logs, or visible UI error messages.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_links",
				description: "Extracts URLs and hyperlinks.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_form_fields",
				description: "Identifies inputs, labels, and forms on screen.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_key_claims",
				description: "Pulls out primary assertions or key points from text.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_visible_content",
				description: "Synthesizes a focused summary of the visible screen.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "compare_items",
				description: "Evaluates similarities and differences (e.g., comparing product features).",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "explain_code",
				description: "Diagnoses and explains code snippets.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "explain_error",
				description: "Provides a plain-English explanation for an extracted error.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "classify_page_type",
				description: "Determines the type of workflow or document currently open.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "identify_next_step",
				description: "Recommends a logical next action.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "detect_missing_information",
				description: "Flags critical gaps in the provided context.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "rewrite_text",
				description: "Adjusts tone, fixes grammar, or reformats general text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "format_as_email",
				description: "Converts raw notes into a drafted email structure.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "convert_to_checklist",
				description: "Structures scattered points into actionable checkboxes.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "create_table",
				description: "Organizes comparative data into a markdown table.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "shorten_text",
				description: "Condenses text into a brief overview.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "expand_text",
				description: "Elaborates on brief points with more detail.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "clean_text",
				description: "Strips out formatting noise and artifacts.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_result",
				description: "Displays general output or text blocks.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_comparison",
				description: "Formats and displays a side-by-side comparison.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_checklist",
				description: "Renders a structured checklist interface.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_warning",
				description: "Surprises prominent alerts or safety boundaries.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "copy_to_clipboard",
				description: "Securely places formatted output into the clipboard.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .noOutput,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "call_local_llm",
				description: "General purpose LLM invocation.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_with_llm",
				description: "LLM-based summarization.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "classify_with_llm",
				description: "LLM-based classification.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_structured_json_with_llm",
				description: "Extract JSON via LLM.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "critique_result_with_llm",
				description: "LLM-based critique.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "verify_output_with_llm",
				description: "Verify output via LLM.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "generate_short_response",
				description: "Generate brief text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "generate_long_response",
				description: "Generate detailed text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "web_search",
				description: "Perform web search.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "fetch_page_text",
				description: "Fetch text from URL.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_web_page",
				description: "Summarize web page.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_search_results",
				description: "Extract links from search.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "compare_web_sources",
				description: "Compare web pages.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_article_content",
				description: "Extract article body.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "detect_paywall",
				description: "Check for paywall.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "identify_primary_topic",
				description: "Identify main topic.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "get_current_url",
				description: "Get active tab URL.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "open_new_tab",
				description: "Open new browser tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "switch_tab",
				description: "Switch to existing tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "close_tab",
				description: "Close active tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "search_in_current_tab",
				description: "Search in current tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "navigate_to_url",
				description: "Navigate active tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_page_title",
				description: "Read browser page title.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_browser_visible_text",
				description: "Read visible web text.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "fill_web_field",
				description: "Fill form field.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "submit_form",
				description: "Submit active form.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "draft_email",
				description: "Draft an email.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_email_thread",
				description: "Summarize email thread.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_email_action_items",
				description: "Extract action items.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "prepare_reply",
				description: "Draft an email reply.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "prepare_followup",
				description: "Draft a followup.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "create_message_summary",
				description: "Summarize chat message.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "open_app",
				description: "Launch an application.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "focus_app",
				description: "Bring app to front.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "quit_app",
				description: "Quit an application.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "switch_window",
				description: "Switch app window.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "press_shortcut",
				description: "Simulate keyboard shortcut.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "scroll_view",
				description: "Scroll the active view.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "click_screen_coordinate",
				description: "Click X/Y coordinate.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "click_ui_element_by_id",
				description: "Click UI element by ID.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "type_text",
				description: "Simulate keystrokes.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "clear_text_field",
				description: "Clear text field.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "split_goal_into_subtasks",
				description: "Split complex goal.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "run_subtasks_parallel",
				description: "Run tasks in parallel.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "merge_results",
				description: "Merge subtask results.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "rank_results",
				description: "Rank multiple items.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "verify_result",
				description: "Verify final result.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "retry_once",
				description: "Retry a failed hook.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "branch_on_result",
				description: "Branch execution path.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
        ]
    }