			HookCapabilityDefinition(
				id: "observe_current_context",
				description: "Captures a snapshot of the active window/app state.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_window_title",
				description: "Reads the title of the active window.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_selected_text",
				description: "Retrieves any user-selected text.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_clipboard",
				description: "Reads the current contents of the system clipboard.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_ax_text",
				description: "Extracts text directly from the macOS Accessibility API.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "run_ocr_once",
				description: "Captures a screen snapshot and runs Optical Character Recognition.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_current_context",
				description: "Produces a general summary of the immediate context.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_entities",
				description: "Identifies names, places, and organizations.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_product_attributes",
				description: "Extracts specific product details (brands, specs).",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_prices",
				description: "Finds monetary values and pricing structures.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_dates",
				description: "Locates timestamps and calendar dates.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_errors",
				description: "Captures stack traces, crash logs, or visible UI error messages.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_links",
				description: "Extracts URLs and hyperlinks.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_form_fields",
				description: "Identifies inputs, labels, and forms on screen.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_key_claims",
				description: "Pulls out primary assertions or key points from text.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_visible_content",
				description: "Synthesizes a focused summary of the visible screen.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "compare_items",
				description: "Evaluates similarities and differences (e.g., comparing product features).",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "explain_code",
				description: "Diagnoses and explains code snippets.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "explain_error",
				description: "Provides a plain-English explanation for an extracted error.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "classify_page_type",
				description: "Determines the type of workflow or document currently open.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "identify_next_step",
				description: "Recommends a logical next action.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "detect_missing_information",
				description: "Flags critical gaps in the provided context.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "rewrite_text",
				description: "Adjusts tone, fixes grammar, or reformats general text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "format_as_email",
				description: "Converts raw notes into a drafted email structure.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "convert_to_checklist",
				description: "Structures scattered points into actionable checkboxes.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "create_table",
				description: "Organizes comparative data into a markdown table.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "shorten_text",
				description: "Condenses text into a brief overview.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "expand_text",
				description: "Elaborates on brief points with more detail.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "clean_text",
				description: "Strips out formatting noise and artifacts.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_result",
				description: "Displays general output or text blocks.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_comparison",
				description: "Formats and displays a side-by-side comparison.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_checklist",
				description: "Renders a structured checklist interface.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "present_warning",
				description: "Surprises prominent alerts or safety boundaries.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "copy_to_clipboard",
				description: "Securely places formatted output into the clipboard.",
				category: .presentation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .noOutput,
				isImplemented: true,
				mappedPrimitive: nil,
				safetyNotes: ""
			),