			HookCapabilityDefinition(
				id: "call_local_llm",
				description: "General purpose LLM invocation.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_with_llm",
				description: "LLM-based summarization.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "classify_with_llm",
				description: "LLM-based classification.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_structured_json_with_llm",
				description: "Extract JSON via LLM.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "critique_result_with_llm",
				description: "LLM-based critique.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "verify_output_with_llm",
				description: "Verify output via LLM.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "generate_short_response",
				description: "Generate brief text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "generate_long_response",
				description: "Generate detailed text.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "web_search",
				description: "Perform web search.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "fetch_page_text",
				description: "Fetch text from URL.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_web_page",
				description: "Summarize web page.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_search_results",
				description: "Extract links from search.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "compare_web_sources",
				description: "Compare web pages.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_article_content",
				description: "Extract article body.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "detect_paywall",
				description: "Check for paywall.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "identify_primary_topic",
				description: "Identify main topic.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "get_current_url",
				description: "Get active tab URL.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "open_new_tab",
				description: "Open new browser tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "switch_tab",
				description: "Switch to existing tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "close_tab",
				description: "Close active tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "search_in_current_tab",
				description: "Search in current tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "navigate_to_url",
				description: "Navigate active tab.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_page_title",
				description: "Read browser page title.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .metadata,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "read_browser_visible_text",
				description: "Read visible web text.",
				category: .observation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "fill_web_field",
				description: "Fill form field.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "submit_form",
				description: "Submit active form.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "draft_email",
				description: "Draft an email.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "summarize_email_thread",
				description: "Summarize email thread.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "extract_email_action_items",
				description: "Extract action items.",
				category: .extraction,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "prepare_reply",
				description: "Draft an email reply.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "prepare_followup",
				description: "Draft a followup.",
				category: .transformation,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "create_message_summary",
				description: "Summarize chat message.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "open_app",
				description: "Launch an application.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "focus_app",
				description: "Bring app to front.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "quit_app",
				description: "Quit an application.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "switch_window",
				description: "Switch app window.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "press_shortcut",
				description: "Simulate keyboard shortcut.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "scroll_view",
				description: "Scroll the active view.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "click_screen_coordinate",
				description: "Click X/Y coordinate.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "click_ui_element_by_id",
				description: "Click UI element by ID.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "type_text",
				description: "Simulate keystrokes.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "clear_text_field",
				description: "Clear text field.",
				category: .computerControl,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .userConfirmation,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "split_goal_into_subtasks",
				description: "Split complex goal.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "run_subtasks_parallel",
				description: "Run tasks in parallel.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "merge_results",
				description: "Merge subtask results.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "rank_results",
				description: "Rank multiple items.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "verify_result",
				description: "Verify final result.",
				category: .reasoning,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .none,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "retry_once",
				description: "Retry a failed hook.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),
			HookCapabilityDefinition(
				id: "branch_on_result",
				description: "Branch execution path.",
				category: .dangerous,
				requiredContextTypes: [.none],
				permission: .none,
				permissionLevel: .unavailable,
				outputType: .text,
				isImplemented: false,
				mappedPrimitive: nil,
				safetyNotes: ""
			),